import hre from "hardhat";
import * as fs from "fs";
import * as path from "path";
import { defineChain, type Chain } from "viem";

const DEPLOYMENTS_JSON = path.resolve(__dirname, "../../../deployments.json");
const DEPLOYMENTS_TS = path.resolve(__dirname, "../../../web/src/config/deployments.ts");

// Custom chain definitions for networks not in viem's built-in list
const CUSTOM_CHAINS: Record<string, Chain> = {
	polkadotTestnet: defineChain({
		id: 420420417,
		name: "Paseo Asset Hub",
		nativeCurrency: { name: "PAS", symbol: "PAS", decimals: 10 },
		rpcUrls: {
			default: { http: ["https://services.polkadothub-rpc.com/testnet"] },
		},
	}),
};

function getChainOverride(): { chain: Chain } | Record<string, never> {
	const chain = CUSTOM_CHAINS[hre.network.name];
	return chain ? { chain } : {};
}

function updateDeployments(key: string, address: string) {
	let data: Record<string, string | null> = {};
	try {
		data = JSON.parse(fs.readFileSync(DEPLOYMENTS_JSON, "utf-8"));
	} catch {
		// File doesn't exist yet
	}
	data[key] = address;

	// Write JSON (for CLI and other tools)
	fs.writeFileSync(DEPLOYMENTS_JSON, JSON.stringify(data, null, 2) + "\n");

	// Write TypeScript (for frontend) — match project formatting (tabs, trailing commas, unquoted keys)
	const fmt = (v: string | null) => (v === null ? "null" : `"${v}"`);
	const tsKeysType = Object.keys(data).map(k => `${k}: string | null`).join("; ");
	const tsLines = Object.entries(data).map(([k, v]) => `\t${k}: ${fmt(v)},`).join("\n");
	const ts = `// Auto-generated by contract deploy scripts — do not edit manually
export const deployments: { ${tsKeysType} } = {
${tsLines}
};
`;
	fs.writeFileSync(DEPLOYMENTS_TS, ts);
}

async function main() {
	const chainOverride = getChainOverride();
	const [walletClient] = await hre.viem.getWalletClients(chainOverride);
	const publicClient = await hre.viem.getPublicClient(chainOverride);

	const contractsDir = path.resolve(__dirname, "../contracts");
	const files = fs.readdirSync(contractsDir).filter(f => f.endsWith(".sol"));

	for (const file of files) {
		const contractName = file.replace(".sol", "");
		console.log(`Deploying ${contractName}...`);
		const artifact = await hre.artifacts.readArtifact(contractName);

		const hash = await walletClient.deployContract({
			abi: artifact.abi,
			bytecode: artifact.bytecode as `0x${string}`,
		});

		const receipt = await publicClient.waitForTransactionReceipt({ hash, timeout: 120_000 });

		if (!receipt.contractAddress) {
			throw new Error(`Deploy tx ${hash} did not create a contract`);
		}

		console.log(`${contractName} deployed to: ${receipt.contractAddress}`);
		
		const key = contractName.charAt(0).toLowerCase() + contractName.slice(1);
		updateDeployments(key, receipt.contractAddress);
	}
	console.log("Updated deployments.json");
}

main().catch((error) => {
	console.error(error);
	process.exitCode = 1;
});
